### ISSUE TITLE
⚠️ **Deprecation Warning** ⚠️ Removal of all gems pre-0.2.0 [2020-07-17]

### ISSUE THREAD

**Issue by thomasrockhu** [codecov/codecov-ruby#87]
We will be deprecating all gems prior 0.2.0. We are moving away from the v1 uploaders, as they are causing a significant percentage of upload timeouts and connection errors. Please upgrade to 0.2.0+ before August 17, 2020 in order to prevent stoppage of service.

**Comment by chrisseaton** [comment]
This was a pretty brutal deprecation. Actually *yanking* gems with a week's notice?

**Comment by thomasrockhu** [comment]
@chrisseaton you're totally right, a week is brutal. We had made the change [here](https://github.com/codecov/codecov-ruby/commit/69d4b00502bae5281573edc8862a787dc6997e01#diff-04c6e90faac2675aa89e2176d2eec7d8) with about 3 weeks notice, but making this issue was an afterthought, and that's my fault.

Unfortunately, we had to move on our side quickly to prevent user issues, and I realize that it wasn't the smoothest way to handle this. Thanks for your feedback, and aside from giving more time, what else could we have done?

**Comment by chrisseaton** [comment]
Sorry I don't know much about the internal issues that caused the need to force people to stop using the gem as such an emergency, so I'll just trust the technical reason was sound and it was doing something really terrible to your network.

I only use `simplecov` as a transitive dependency, so I would never think to be reading your README every three weeks in order to catch this message. All I knew is my app with pinned gem versions just suddenly stopped working one day.

Even leaving the gems but disabling their end-point would have been more convenient for me. I don't think I actually was using them in the particular configuration I was running, so if you'd done that I could have carried on happily.

**Comment by Fire-** [comment]
Just to give some additional feedback - this change went unnoticed as we'd pinned versions ( and I suppose there aren't any deprecation communications for enterprise either? ) and broke several builds that relied upon the gem existing. A reporting failure on that endpoint with an error message that explained what was happening would have been far more noticeable without breaking builds due to a dep failure.

**Comment by thomasrockhu** [comment]
@chrisseaton and @Fire- I really appreciate the feedback here, and I am deeply sorry that this was not a smooth transition. We do not anticipate a major change like this happening again, but if so, we will take measures to be as communicative as possible. Thanks everyone.

**Comment by elia** [comment]
@thomasrockhu we had the same issue in the solidus ecosystem, with a decent number of extensions failing, I think @chrisseaton's suggestion would still be good to follow, _unyanking_ the v0.1 gems and disabling the endpoints.

An alternative would be to release a patch level v0.1.x that disables the bad behavior and prints some kind of warning when required.

**Comment by thomasrockhu** [comment]
@elia, these are very good points. In the hopes that it is not too late, I am releasing version `0.1.21` which will mirror `0.2.8`. Unfortunately, we will be unable to [unyank the gems](https://blog.rubygems.org/2015/04/13/permadelete-on-yank.html). I really appreciate your feedback here.

**Comment by elia** [comment]
Thanks 🙏 really appreciated, that well at least solve the issue for Gemfiles with a ~> 0.1.0 requirement (which was our case).

**Comment by thomasrockhu** [comment]
I'm going to close this issue as a result, thanks again for all the feedback everyone. This was not as smooth as we had hoped, and I apologize for any difficulties faced. We'll do better in the future.
